/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.Persoana;
import service.PersoanaServiceImpl;
import java.awt.event.*;
import javax.swing.JTable;

import java.util.Arrays;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Valeriu Ungureanu
 */
public class FereastraPrincipala extends javax.swing.JFrame {

    /**
     * Creates new form FereastraPrincipala
     */
    public FereastraPrincipala() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jNumeLabel = new javax.swing.JLabel();
        jTextNume = new javax.swing.JTextField();
        jPrenumeLabel = new javax.swing.JLabel();
        jTextPrenume = new javax.swing.JTextField();
        jButtonSave = new javax.swing.JButton();
        jPrinteazaToatePersoanele = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jID = new javax.swing.JTextField();
        jButtonUpdate = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jIDdelete = new javax.swing.JTextField();
        jButtonDelete = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePerson = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DAO");

        jNumeLabel.setText("Nume:");

        jTextNume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNumeActionPerformed(evt);
            }
        });

        jPrenumeLabel.setText("Prenume:");

        jTextPrenume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPrenumeActionPerformed(evt);
            }
        });

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jPrinteazaToatePersoanele.setText("Afisează toate persoanele");
        jPrinteazaToatePersoanele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrinteazaToatePersoaneleActionPerformed(evt);
            }
        });

        jLabel1.setText("Update user după ID:");

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jLabel2.setText("Șterge user după ID:");

        jButtonDelete.setText("Șterge");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jTablePerson.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "ID", "Nume", "Prenume"
                }
        ));
        jTablePerson.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePersonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePerson);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jPrenumeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jNumeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(45, 45, 45)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jTextNume)
                                                        .addComponent(jTextPrenume, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jID, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                                                        .addComponent(jIDdelete)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jPrinteazaToatePersoanele)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jButtonUpdate)
                                                                .addGap(29, 29, 29)
                                                                .addComponent(jButtonDelete)
                                                                .addGap(11, 11, 11)))
                                                .addGap(18, 18, 18)
                                                .addComponent(jButtonSave)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonDelete, jButtonUpdate});

        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jNumeLabel)
                                                        .addComponent(jTextNume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jPrenumeLabel)
                                                        .addComponent(jTextPrenume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(52, 52, 52)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(31, 31, 31)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jIDdelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonUpdate)
                                        .addComponent(jButtonDelete)
                                        .addComponent(jButtonSave))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                .addComponent(jPrinteazaToatePersoanele))
        );

        pack();
    }// </editor-fold>

    private PersoanaServiceImpl service = new PersoanaServiceImpl();

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {
        Persoana persoana = new Persoana(jTextNume.getText(), jTextPrenume.getText());
        service.addPersoana(persoana);

        DefaultTableModel table = (DefaultTableModel) jTablePerson.getModel();
        String tab[] = {String.valueOf(persoana.getID()), persoana.getNume(), persoana.getPreNume()};
        table.addRow(tab);
        System.out.println("A fost creata o persoana din GUI");

        jTextNume.setText("");    // TODO add your handling code here:
        jTextPrenume.setText("");

    }

    private void jTextNumeActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextPrenumeActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jPrinteazaToatePersoaneleActionPerformed(java.awt.event.ActionEvent evt) {

        service.printeazaToatePersoanele();
//        PersoanaService s1 = new PersoanaService();
//        s1.printeazaToatePersoanele();
        // TODO add your handling code here:
    }

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {
        DefaultTableModel table = (DefaultTableModel) jTablePerson.getModel();
        int selectedRow = jTablePerson.getSelectedRow();
        service.update(Integer.valueOf(String.valueOf(table.getValueAt(selectedRow, 0))));
        // table.setValueAt(table, ERROR, NORMAL);// TODO add your handling code here:
    }

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {

        DefaultTableModel table = (DefaultTableModel) jTablePerson.getModel();
        int selectedRow = jTablePerson.getSelectedRow();
        service.delete(Integer.valueOf(String.valueOf(table.getValueAt(selectedRow, 0))));
        table.removeRow(selectedRow);
// TODO add your handling code here:
//        System.out.println("Persoana cu ID = "+jIDdelete.getText()+" a fost stearsa");
    }

    private void jTablePersonMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        DefaultTableModel table = (DefaultTableModel) jTablePerson.getModel();
        int selectedRow = jTablePerson.getSelectedRow();
        String nume=String.valueOf(table.getValueAt(selectedRow, 1));
        String preNume=String.valueOf(table.getValueAt(selectedRow, 2));
        jTextNume.setText(nume);
        jTextPrenume.setText(preNume);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

//   PersoanaService service = new PersoanaService();
//    Persoana persoana1 = new Persoana("John","Snow");
//    service.create(persoana1);
//        Persoana persoana2 = new Persoana("Vasile", "Botnari");
//        service.create(persoana2);
//        Persoana persoana3 = new Persoana("John", "Snow");
//        service.create(persoana3);
//        Persoana persoana4 =  service.read(30);
//        System.out.println(persoana3);
//        service.printeazaToatePersoanele();
////        System.out.println(Arrays.toString(service.readAll()));
////        service.update(2);
////        service.read(2);
////        service.printeazaToatePersoanele();
//        service.delete(2);
//        service.printeazaToatePersoanele();
//        Persoana persoana5 = new Persoana("Vasile2", "Botnari2");
//        service.create(persoana5);
//        System.out.println("Am creat o noua persoana");
//        service.printeazaToatePersoanele();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FereastraPrincipala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FereastraPrincipala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FereastraPrincipala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FereastraPrincipala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FereastraPrincipala().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify
    private javax.swing.JToggleButton jButtonDelete;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JToggleButton jButtonUpdate;
    private javax.swing.JTextField jID;
    private javax.swing.JTextField jIDdelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jNumeLabel;
    private javax.swing.JLabel jPrenumeLabel;
    private javax.swing.JButton jPrinteazaToatePersoanele;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePerson;
    private javax.swing.JTextField jTextNume;
    private javax.swing.JTextField jTextPrenume;
    // End of variables declaration
}

