/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import model.Persoana;
import service.PersoanaServiceImpl;
import java.awt.event.*;
import javax.swing.JTable;

import java.util.Arrays;

/**
 *
 * @author Vadim
 */
public class FereastraPrincipala extends javax.swing.JFrame {

    /**
     * Creates new form FereastraPrincipala
     */
    public FereastraPrincipala() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNumeLabel = new javax.swing.JLabel();
        jNume = new javax.swing.JTextField();
        jPrenumeLabel = new javax.swing.JLabel();
        jPrenume = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPrinteazaToatePersoanele = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jID = new javax.swing.JTextField();
        jUpdate = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jIDdelete = new javax.swing.JTextField();
        jDeleteID = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DAO");

        jNumeLabel.setText("Nume:");

        jNume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNumeActionPerformed(evt);
            }
        });

        jPrenumeLabel.setText("Prenume:");

        jPrenume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrenumeActionPerformed(evt);
            }
        });

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPrinteazaToatePersoanele.setText("Afisează toate persoanele");
        jPrinteazaToatePersoanele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrinteazaToatePersoaneleActionPerformed(evt);
            }
        });

        jLabel1.setText("Update user după ID:");

        jUpdate.setText("Update");
        jUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateActionPerformed(evt);
            }
        });

        jLabel2.setText("Șterge user după ID:");

        jDeleteID.setText("Șterge");
        jDeleteID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPrinteazaToatePersoanele))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPrenumeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jNumeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jNume)
                                        .addComponent(jPrenume, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jID, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                                    .addComponent(jIDdelete))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jDeleteID)
                            .addComponent(jUpdate))
                        .addGap(41, 41, 41)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jDeleteID, jUpdate});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNumeLabel)
                    .addComponent(jNume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPrenumeLabel)
                    .addComponent(jPrenume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUpdate))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jIDdelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDeleteID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPrinteazaToatePersoanele)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private PersoanaServiceImpl service = new PersoanaServiceImpl();
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Persoana persoana = new Persoana(jNume.getText(),jPrenume.getText());
    service.create(persoana);
        System.out.println("A fost creata o persoana din GUI");
        jNume.setText("");    // TODO add your handling code here:
        jPrenume.setText("");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jNumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNumeActionPerformed

    private void jPrenumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrenumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPrenumeActionPerformed

    private void jPrinteazaToatePersoaneleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrinteazaToatePersoaneleActionPerformed
    
        service.printeazaToatePersoanele();//    PersoanaService  s1 = new PersoanaService();
//    s1.printeazaToatePersoanele();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPrinteazaToatePersoaneleActionPerformed

    private void jUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateActionPerformed
    service.update(Integer.parseInt(jID.getText()));    // TODO add your handling code here:
    }//GEN-LAST:event_jUpdateActionPerformed

    private void jDeleteIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteIDActionPerformed
    service.delete(Integer.parseInt(jIDdelete.getText()));    // TODO add your handling code here:
//        System.out.println("Persoana cu ID = "+jIDdelete.getText()+" a fost stearsa");
    }//GEN-LAST:event_jDeleteIDActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     
//   PersoanaService service = new PersoanaService();
//    Persoana persoana1 = new Persoana("John","Snow");
//    service.create(persoana1);
//        Persoana persoana2 = new Persoana("Vasile", "Botnari");
//        service.create(persoana2);
//        Persoana persoana3 = new Persoana("John", "Snow");
//        service.create(persoana3);
//        Persoana persoana4 =  service.read(30);
//        System.out.println(persoana3);
//        service.printeazaToatePersoanele();
////        System.out.println(Arrays.toString(service.readAll()));
////        service.update(2);
////        service.read(2);
////        service.printeazaToatePersoanele();
//        service.delete(2);
//        service.printeazaToatePersoanele();
//        Persoana persoana5 = new Persoana("Vasile2", "Botnari2");
//        service.create(persoana5);
//        System.out.println("Am creat o noua persoana");
//        service.printeazaToatePersoanele();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FereastraPrincipala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FereastraPrincipala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FereastraPrincipala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FereastraPrincipala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FereastraPrincipala().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JToggleButton jDeleteID;
    private javax.swing.JTextField jID;
    private javax.swing.JTextField jIDdelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jNume;
    private javax.swing.JLabel jNumeLabel;
    private javax.swing.JTextField jPrenume;
    private javax.swing.JLabel jPrenumeLabel;
    private javax.swing.JButton jPrinteazaToatePersoanele;
    private javax.swing.JToggleButton jUpdate;
    // End of variables declaration//GEN-END:variables
}
